on: [push, pull_request]
name: Test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install Tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
      - name: Build
        working-directory: ${{env.working_directory}}
        run: |
          go mod tidy
          go build main.go
      - name: Static Check
        working-directory: ${{env.working_directory}}
        run: |
          staticcheck ./...
          go vet -v ./...
          gosec ./...

      - name: Test
        run: go test ./... -count=1
